add user request manager
OilerNetwork/fossil-offchain-processor pull request #7
Opened 2024-06-12 02:59 UTC by c0np4nn4

2024-06-12 04:29 UTC, ametel01 requested changes

2024-06-12 04:29 UTC, ametel01 commented on crates/request-manager/src/handlers/get_storage_value.rs
> +                    Err(_) => response_with_status(StatusCode::BAD_REQUEST, "Failed to parse JSON"),
consider better error logging eg
```rust
Err(err) => {
    eprintln!("Failed to parse JSON: {:?}", err);
    response_with_status(StatusCode::BAD_REQUEST, "Failed to parse JSON")
},
```

2024-06-12 04:29 UTC, ametel01 commented on crates/request-manager/src/main.rs
>      let listener = tokio::net::TcpListener::bind("0.0.0.0:8000").await.unwrap();
be more explicit with logging and errors handling eg:

```rust
let listener = match tokio::net::TcpListener::bind("0.0.0.0:8000").await {
        Ok(listener) => {
            info!("Listening on http://{}", listener.local_addr().unwrap());
            listener
        }
        Err(e) => {
            error!("Failed to bind to address: {}", e);
            return;
        }
    };

    if let Err(e) = axum::serve(listener, app).await {
        error!("Server error: {}", e);
    }
```

2024-06-25 03:13 UTC, srj31 commented on crates/starknet-handler/src/artifacts/FactRegistry.json
can be deleted, its unnecessary now

2024-06-25 03:13 UTC, srj31 commented on crates/starknet-handler/src/artifacts/fossil_L1HeaderStore.contract_class.json
can be deleted, its unnecessary

2024-06-25 03:15 UTC, srj31 commented on crates/starknet-handler/src/interface/mod.rs
interface/ is no longer used in the starknet-handler

2024-06-25 03:53 UTC, ametel01 commented
We are completely missing all the functionalities, the request manager should receive the request from the user exposing an endpoint eg: "get-storage" and call the necessary crates given the sequence diagram. This seems to be only spinning up a server

2024-08-07 02:58 UTC, closed without merging